//! OpenClaw (formerly Clawdbot / Moltbot): `~/.openclaw/openclaw.json` (JSON5) with custom
//! providers under `models.providers.<id>` (same shape as pi's models.json) and the default
//! model in `agents.defaults.model.primary` ("provider/model").
//!
//! The config schema is strict (an unknown key stops the gateway), so only documented keys
//! are ever added: provider display names live in the AgentPlus store, not in the file. The
//! file is written back as plain pretty JSON, so a file using JSON5-only syntax (comments,
//! unquoted keys, trailing commas…) is shown read-only.
//!
//! `~/.openclaw/agents/<id>/agent/models.json` is generated by OpenClaw and its
//! baseUrl / apiKey win over openclaw.json, so address / key changes are mirrored there.


use super::{Plan, Endpoint};
use super::pimodels::{self, Dirty, Flavor, Fmt};
use crate::model::*;
use crate::process::Install;
use crate::util::*;
use crate::i18n::l;
use anyhow::{anyhow, Result};
use serde_json::{json, Value};
use std::path::PathBuf;

pub const ID: &str = "openclaw";
pub const NAME: &str = "OpenClaw";
#[allow(dead_code)]
pub const MARKER: &str = "openclaw.json";
#[allow(dead_code)]
pub const WSL_SCRIPT: &str = "openclaw --version 2>/dev/null; (pgrep -x openclaw-gatewa || pgrep -x openclaw) >/dev/null && echo @running; true";
#[allow(dead_code)]
pub const WSL_MARKER: &str = ".openclaw/openclaw.json";

/// `~/.openclaw` (or `$OPENCLAW_STATE_DIR`, or the folder picked in AgentPlus).
pub fn default_dir() -> PathBuf {
    if let Some(r) = pimodels::test_root() {
        return r.join("openclaw");
    }
    if let Some(d) = super::dir_override(ID) {
        return d;
    }
    if let Some(d) = pimodels::env_var("OPENCLAW_STATE_DIR") {
        return crate::env::resolve_path(&d);
    }
    home().join(".openclaw")
}

fn config_path() -> PathBuf {
    if pimodels::test_root().is_none() && super::dir_override(ID).is_none() {
        if let Some(p) = pimodels::env_var("OPENCLAW_CONFIG_PATH") {
            return crate::env::resolve_path(&p);
        }
    }
    default_dir().join("openclaw.json")
}

fn fmt() -> Fmt {
    Fmt { agent: ID, flavor: Flavor::OpenClaw, path: config_path(), ptr: "/models/providers", auth: None, env_file: Some(default_dir().join(".env")) }
}

/// The generated per-agent model files (`agents/<id>/agent/models.json`).
fn generated() -> Vec<PathBuf> {
    let Ok(rd) = std::fs::read_dir(default_dir().join("agents")) else { return vec![] };
    let mut out: Vec<PathBuf> = rd.flatten().map(|e| e.path().join("agent").join("models.json")).filter(|p| p.is_file()).collect();
    out.sort();
    out
}

/// json5 hands numbers over as floats; turn whole ones back into integers.
fn integers(v: &mut Value) {
    match v {
        Value::Number(n) => {
            if let Some(f) = n.as_f64().filter(|f| n.is_f64() && f.fract() == 0.0 && f.abs() < 9.0e15) {
                *v = if f >= 0.0 { json!(f as u64) } else { json!(f as i64) };
            }
        }
        Value::Array(a) => a.iter_mut().for_each(integers),
        Value::Object(o) => o.values_mut().for_each(integers),
        _ => {}
    }
}

/// (config, meta, why it is read-only). A missing file reads as `{}`.
fn load() -> Result<(Value, TextMeta, Option<String>)> {
    let p = config_path();
    if !p.exists() {
        return Ok((json!({}), TextMeta::NEW, None));
    }
    let (text, meta) = read_text(&p)?;
    if let Ok(v) = serde_json::from_str::<Value>(&text) {
        return Ok((v, meta, None));
    }
    let mut v: Value = json5::from_str(&text).map_err(|e| anyhow!(tr!("{} 解析失败：{e}", "Failed to parse {}: {e}", display_path(&p))))?;
    integers(&mut v);
    Ok((v, meta, Some(l("openclaw.json 用了 JSON5 写法（注释、无引号的键、结尾逗号等），AgentPlus 写回会丢掉这些格式，已切换为只读。", "openclaw.json uses JSON5 syntax (comments, unquoted keys, trailing commas, etc.) that AgentPlus would lose on write. Switched to read-only.").into())))
}

fn has_include(v: &Value) -> bool {
    match v {
        Value::Object(o) => o.contains_key("$include") || o.values().any(has_include),
        Value::Array(a) => a.iter().any(has_include),
        _ => false,
    }
}

/// (primary, fallbacks) of `agents.defaults.model` (a "provider/model" string or `{ primary, fallbacks }`).
fn default_model(cfg: &Value) -> (Option<String>, Vec<String>) {
    match cfg.pointer("/agents/defaults/model") {
        Some(Value::String(s)) => (Some(s.clone()).filter(|s| !s.is_empty()), vec![]),
        Some(o @ Value::Object(_)) => (
            o.get("primary").and_then(|x| x.as_str()).map(String::from).filter(|s| !s.is_empty()),
            str_list(o.get("fallbacks")).unwrap_or_default(),
        ),
        _ => (None, vec![]),
    }
}

fn split_ref(r: &str) -> (&str, Option<&str>) {
    match r.split_once('/') {
        Some((p, m)) => (p, Some(m)),
        None => (r, None),
    }
}

pub fn detect() -> Install {
    let mut inst = Install::default();
    let npm = dirs::data_dir().map(|d| d.join("npm"));
    if let Some(pkg) = npm.as_ref().map(|d| d.join("node_modules").join("openclaw").join("package.json")) {
        if let Ok(text) = std::fs::read_to_string(pkg) {
            inst.installed = true;
            inst.version = serde_json::from_str::<Value>(&text).ok().and_then(|v| v.get("version").and_then(|x| x.as_str()).map(String::from));
            return inst;
        }
    }
    let shims = [npm.map(|d| d.join("openclaw.cmd")), dirs::data_local_dir().map(|d| d.join("pnpm").join("openclaw.cmd"))];
    inst.installed = shims.iter().flatten().any(|p| p.exists());
    inst
}

pub fn state(inst: &Install) -> AgentState {
    let f = fmt();
    let gen = generated();
    let mut files = vec![f.file()];
    files.extend(gen.iter().map(|p| display_path(p)));
    let mut st = AgentState {
        id: ID.into(),
        name: NAME.into(),
        installed: inst.installed,
        version: inst.version.clone(),
        running: inst.running,
        mode: "multi".into(),
        config_dir: default_dir().to_string_lossy().to_string(),
        files,
        current_provider: None,
        providers: vec![],
        catalog: None,
        catalog_file: None,
        settings: vec![],
        current: vec![],
        notes: vec![l("OpenClaw 的 gateway 会热加载配置，改动保存后即生效。", "The OpenClaw gateway hot-reloads its config, so changes take effect once saved.").into()],
        readonly: false,
        fixed_pending: false,
        fixed_prompt: false,
        restartable: false,
        model_fields: vec![],
    };
    if !gen.is_empty() {
        st.notes.push(l("agents/*/agent/models.json 是 OpenClaw 生成的，其中的 baseUrl / apiKey 优先于 openclaw.json；改地址或密钥时 AgentPlus 会一并同步。", "agents/*/agent/models.json is generated by OpenClaw and its baseUrl / apiKey override openclaw.json. AgentPlus updates them too when you change a base URL or API key.").into());
    }
    if !config_path().exists() {
        let h = home();
        if [".clawdbot", ".moltbot"].iter().any(|d| h.join(d).exists()) {
            st.notes.push(l("发现旧版 Clawdbot / Moltbot 的配置目录；运行一次 openclaw 会迁移到 ~/.openclaw。", "Found an old Clawdbot / Moltbot config folder. Run openclaw once to migrate it to ~/.openclaw.").into());
        }
    }
    let root = pimodels::load_store();
    let cfg = match load() {
        Ok((cfg, _, ro)) => {
            if let Some(why) = ro {
                st.readonly = true;
                st.notes.push(why);
            }
            cfg
        }
        Err(e) => {
            st.notes.push(e.to_string());
            st.readonly = true;
            return st;
        }
    };
    if has_include(&cfg) {
        st.notes.push(l("openclaw.json 用了 $include，被包含文件里的供应商这里看不到。", "openclaw.json uses $include; providers in included files are not shown here.").into());
    }
    if cfg.pointer("/models/mode").and_then(|x| x.as_str()) == Some("replace") {
        st.notes.push(l("models.mode = \"replace\"：只有这里列出的供应商可用，内置供应商被替换掉了。", "models.mode = \"replace\": only the providers listed here are available; the built-in providers are replaced.").into());
    }
    st.providers = f.providers(&cfg, &root, None);

    let (primary, fallbacks) = default_model(&cfg);
    let on: Vec<&Provider> = st.providers.iter().filter(|p| p.enabled).collect();
    let vis: usize = on.iter().map(|p| p.models.iter().filter(|m| m.visible).count()).sum();
    st.current = vec![
        Kv::text(l("自定义供应商", "Custom providers"), if on.is_empty() { l("无", "None").into() } else { on.iter().map(|p| p.name.as_str()).collect::<Vec<_>>().join(l("、", ", ")) }),
        Kv::mono(l("默认模型", "Default model"), primary.unwrap_or_else(|| "-".into())),
    ];
    if !fallbacks.is_empty() {
        st.current.push(Kv::mono(l("备用模型", "Fallback models"), fallbacks.join(", ")));
    }
    st.current.push(Kv::text(l("可见模型", "Visible models"), tr!("{vis} 个", "{vis}")));
    st.current.push(Kv::mono(l("配置文件", "Config file"), f.file()));
    st
}

pub fn provider_endpoint(id: &str) -> Result<Endpoint> {
    let (cfg, _, _) = load()?;
    fmt().endpoint(id, &cfg, &pimodels::load_store())
}

pub fn plan(ops: &[Op], dry_run: bool) -> Result<Plan> {
    let f = fmt();
    let (mut cfg, meta, readonly) = load()?;
    let cfg0 = cfg.clone();
    let mut root = pimodels::load_store();
    let mut none = None;
    let mut diff = Diff::default();
    let mut dirty = Dirty::default();
    let ef = f.file();

    for op in ops {
        if f.apply(op, &mut cfg, &mut root, &mut none, &mut diff, &mut dirty)? {
            continue;
        }
        match op {
            Op::SetCurrentProvider { .. } => return Err(anyhow!(l("OpenClaw 可以同时用多个供应商：按启用/停用管理，默认模型在 OpenClaw 里设置", "OpenClaw can use several providers at once: manage them by enabling/disabling, and set the default model in OpenClaw."))),
            Op::SetModelRoles { .. } => return Err(anyhow!(l("只有 Claude Code 需要分配模型角色", "Only Claude Code needs model roles."))),
            Op::SetSetting { key, .. } => return Err(anyhow!(tr!("OpenClaw 没有设置项 {key}", "OpenClaw has no setting {key}"))),
            Op::ImportProvider { .. } => unreachable!("resolved in adapters::plan"),
            _ => unreachable!("handled by pimodels"),
        }
    }

    // Don't leave the default / fallback models pointing at something that was just removed.
    if dirty.cfg {
        let gone = |r: &str| {
            let (p, m) = split_ref(r);
            f.has_model(&cfg0, p, m) && !f.has_model(&cfg, p, m)
        };
        let (primary, fallbacks) = default_model(&cfg);
        let primary_gone = primary.filter(|p| gone(p));
        let fallbacks_gone: Vec<bool> = fallbacks.iter().map(|r| gone(r)).collect();
        if let Some(p) = primary_gone {
            let model = cfg.pointer_mut("/agents/defaults").and_then(|d| d.as_object_mut()).unwrap();
            if model.get("model").map(|m| m.is_string()).unwrap_or(false) {
                model.remove("model");
            } else if let Some(o) = model.get_mut("model").and_then(|m| m.as_object_mut()) {
                o.remove("primary");
            }
            diff.push(&ef, tr!("- agents.defaults.model.primary（{p} 已移除，OpenClaw 会改用内置默认模型）", "- agents.defaults.model.primary ({p} was removed; OpenClaw will use its built-in default model)"), false);
        }
        if fallbacks_gone.contains(&true) {
            let mut keep = vec![];
            for (r, g) in fallbacks.iter().zip(&fallbacks_gone) {
                if *g {
                    diff.push(&ef, format!("agents.defaults.model.fallbacks - \"{r}\""), false);
                } else {
                    keep.push(json!(r));
                }
            }
            cfg["agents"]["defaults"]["model"]["fallbacks"] = Value::Array(keep);
        }
    }

    // Mirror address / key changes into the generated per-agent models.json files.
    let mut gen_out: Vec<(PathBuf, Value, TextMeta)> = vec![];
    if dirty.cfg {
        let now = f.providers_of(&cfg).cloned().unwrap_or_default();
        let old = f.providers_of(&cfg0).cloned().unwrap_or_default();
        let changes: Vec<(String, &'static str, Value)> = now
            .iter()
            .filter_map(|(id, def)| old.get(id).map(|o| (id, def, o)))
            .flat_map(|(id, def, o)| {
                ["baseUrl", "apiKey"].into_iter().filter_map(move |k| {
                    let v = def.get(k)?;
                    (o.get(k) != Some(v)).then(|| (id.clone(), k, v.clone()))
                })
            })
            .collect();
        if !changes.is_empty() {
            for path in generated() {
                let Ok((mut g, gm)) = read_json(&path) else { continue };
                let mut touched = false;
                for (id, k, v) in &changes {
                    if let Some(p) = g.pointer_mut(&crate::util::jptr(&["providers", id])).and_then(|p| p.as_object_mut()) {
                        if p.get(*k) != Some(v) {
                            p.insert(k.to_string(), v.clone());
                            let shown = if *k == "apiKey" { mask_key(v.as_str().unwrap_or("")) } else { v.as_str().unwrap_or("").to_string() };
                            diff.push(&display_path(&path), tr!("providers.{id}.{k} = {shown}（同步生成文件）", "providers.{id}.{k} = {shown} (synced to generated file)"), true);
                            touched = true;
                        }
                    }
                }
                if touched {
                    gen_out.push((path, g, gm));
                }
            }
        }
    }

    if dirty.cfg && readonly.is_some() {
        return Err(anyhow!(l("openclaw.json 用了 JSON5 写法，为避免丢失注释和格式不写入", "openclaw.json uses JSON5 syntax; not writing to avoid losing comments and formatting")));
    }
    let mut written = vec![];
    let mut backup_dir = None;
    if !dry_run && dirty.cfg {
        let mut targets = vec![config_path()];
        targets.extend(gen_out.iter().map(|g| g.0.clone()));
        backup_dir = Some(pimodels::backup_files(ID, &targets)?);
        if let Some(d) = config_path().parent() {
            std::fs::create_dir_all(d)?;
        }
        write_json(&config_path(), &cfg, meta)?;
        written.push(config_path());
        for (p, g, m) in &gen_out {
            write_json(p, g, *m)?;
            written.push(p.clone());
        }
    }
    if !dry_run && dirty.store {
        pimodels::save_store(&root)?;
    }
    Ok((diff, written, backup_dir))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{ModelInput, ProviderInput};

    const JSON5: &str = r#"// OpenClaw config
{
  agents: { defaults: { model: { primary: "myproxy/glm-5", fallbacks: [] } } },
  models: { mode: "merge",
    providers: { myproxy: {
      baseUrl: "https://example.com/v1", apiKey: "${MYPROXY_API_KEY}", api: "openai-completions",
      models: [{ id: "glm-5", name: "GLM 5", reasoning: false, input: ["text"],
                 cost: {input:0,output:0,cacheRead:0,cacheWrite:0}, contextWindow: 200000, maxTokens: 32000 }] } } },
}
"#;

    const STRICT: &str = r#"{
  "agents": {
    "defaults": {
      "model": {
        "primary": "myproxy/glm-5",
        "fallbacks": [
          "myproxy/glm-4.6",
          "anthropic/claude-opus-4-6"
        ]
      },
      "workspace": "~/work"
    }
  },
  "models": {
    "mode": "merge",
    "providers": {
      "myproxy": {
        "baseUrl": "https://example.com/v1",
        "apiKey": "${MYPROXY_API_KEY}",
        "api": "openai-completions",
        "models": [
          {
            "id": "glm-5",
            "name": "GLM 5",
            "reasoning": false,
            "input": [
              "text"
            ],
            "cost": {
              "input": 0,
              "output": 0,
              "cacheRead": 0,
              "cacheWrite": 0
            },
            "contextWindow": 200000,
            "maxTokens": 32000
          },
          {
            "id": "glm-4.6",
            "name": "GLM 4.6"
          }
        ]
      },
      "vault": {
        "baseUrl": "https://vault.example.com/v1",
        "apiKey": {
          "source": "exec",
          "provider": "op",
          "id": "relay"
        },
        "api": "anthropic-messages",
        "models": []
      },
      "plain": {
        "baseUrl": "https://plain.example.com/v1",
        "apiKey": "sk-plain-secret-4321",
        "api": "openai-responses",
        "models": [
          {
            "id": "gpt-x",
            "name": "gpt-x"
          }
        ]
      }
    }
  },
  "channels": {
    "telegram": {
      "enabled": true
    }
  },
  "gateway": {
    "port": 18789
  }
}
"#;

    const GENERATED: &str = r#"{
  "providers": {
    "myproxy": {
      "baseUrl": "https://example.com/v1",
      "apiKey": "sk-resolved-old-1111",
      "api": "openai-completions",
      "models": []
    },
    "other": {
      "baseUrl": "https://other.example.com"
    }
  }
}
"#;

    struct Guard(PathBuf);
    impl Drop for Guard {
        fn drop(&mut self) {
            pimodels::TEST_ROOT.with(|t| *t.borrow_mut() = None);
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    fn setup(name: &str, cfg: Option<&str>) -> Guard {
        let root = std::env::temp_dir().join(format!("agentplus-openclaw-test-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let d = root.join("openclaw");
        std::fs::create_dir_all(d.join("agents").join("main").join("agent")).unwrap();
        if let Some(c) = cfg {
            std::fs::write(d.join("openclaw.json"), c).unwrap();
        }
        std::fs::write(d.join("agents/main/agent/models.json"), GENERATED).unwrap();
        std::fs::write(d.join(".env"), "PLAIN_ONLY=1\nFROM_DOTENV=sk-dotenv-2222\n").unwrap();
        pimodels::TEST_ROOT.with(|t| *t.borrow_mut() = Some(root.clone()));
        pimodels::TEST_ENV.with(|e| *e.borrow_mut() = vec![("MYPROXY_API_KEY".into(), "sk-env-proxy-3333".into())]);
        Guard(root)
    }

    fn cfg() -> Value {
        serde_json::from_str(&std::fs::read_to_string(config_path()).unwrap()).unwrap()
    }
    fn gen() -> Value {
        serde_json::from_str(&std::fs::read_to_string(default_dir().join("agents/main/agent/models.json")).unwrap()).unwrap()
    }
    fn lines(d: &Diff) -> String {
        d.groups.iter().flat_map(|g| g.lines.iter().map(move |l| format!("{} | {}", g.file, l.text))).collect::<Vec<_>>().join("\n")
    }
    fn edit(id: &str, name: &str, url: &str, api: &str, key: Option<&str>) -> Op {
        Op::UpsertProvider { provider: ProviderInput { id: Some(id.into()), name: name.into(), base_url: url.into(), api: api.into(), api_key: key.map(String::from), models: vec![], key_from_library: None, official_auth: None } }
    }

    #[test]
    fn json5_is_readonly_but_readable() {
        let _g = setup("json5", Some(JSON5));
        let st = state(&Install::default());
        assert!(st.readonly);
        let p = st.providers.iter().find(|p| p.id == "myproxy").unwrap();
        assert_eq!(p.api, "chat");
        assert!(p.has_key);
        assert_eq!(p.models[0].context, Some(200000));
        assert!(st.current.iter().any(|k| k.v == "myproxy/glm-5"));
        assert_eq!(provider_endpoint("myproxy").unwrap().1.as_deref(), Some("sk-env-proxy-3333"));
        let before = std::fs::read(config_path()).unwrap();
        assert!(plan(&[Op::DeleteModel { provider: "myproxy".into(), model: "glm-5".into() }], false).is_err());
        assert_eq!(std::fs::read(config_path()).unwrap(), before);
    }

    #[test]
    fn reads_state_and_keys() {
        let _g = setup("state", Some(STRICT));
        let st = state(&Install::default());
        assert!(!st.readonly, "{:?}", st.notes);
        let v = st.providers.iter().find(|p| p.id == "vault").unwrap();
        assert!(v.has_key && v.api == "anthropic");
        assert_eq!(provider_endpoint("vault").unwrap().1, None);
        assert_eq!(provider_endpoint("plain").unwrap(), ("https://plain.example.com/v1".into(), Some("sk-plain-secret-4321".into()), "responses".into()));
        assert!(st.notes.iter().any(|n| n.contains("热加载")));
        // The temp dir can be outside home (CI), where display_path keeps native separators.
        assert!(st.files.iter().any(|f| f.replace('\\', "/").ends_with("agents/main/agent/models.json")));
        let dump = format!("{:?}", st);
        assert!(!dump.contains("sk-plain-secret") && !dump.contains("sk-env-proxy"));
        // ${VAR} from ~/.openclaw/.env.
        let mut c = cfg();
        c["models"]["providers"]["plain"]["apiKey"] = json!("${FROM_DOTENV}");
        std::fs::write(config_path(), serde_json::to_string(&c).unwrap()).unwrap();
        assert_eq!(provider_endpoint("plain").unwrap().1.as_deref(), Some("sk-dotenv-2222"));
        c["models"]["providers"]["plain"]["apiKey"] = json!("${NOT_SET}");
        std::fs::write(config_path(), serde_json::to_string(&c).unwrap()).unwrap();
        assert_eq!(provider_endpoint("plain").unwrap().1, None);
    }

    #[test]
    fn create_edit_delete_provider() {
        let _g = setup("crud", Some(STRICT));
        let create = Op::UpsertProvider {
            provider: ProviderInput { id: None, name: "My Relay".into(), base_url: "https://r.example.com/v1".into(), api: "chat".into(), api_key: Some("sk-relay-key-abcd".into()), models: vec!["m1".into()], key_from_library: None, official_auth: None },
        };
        let (d, w, _) = plan(&[create], false).unwrap();
        assert!(lines(&d).contains("••••abcd") && !lines(&d).contains("sk-relay"));
        assert_eq!(w, vec![config_path()]);
        let p = &cfg()["models"]["providers"]["my-relay"];
        assert_eq!(p, &json!({ "baseUrl": "https://r.example.com/v1", "api": "openai-completions", "models": [{ "id": "m1", "name": "m1" }], "apiKey": "sk-relay-key-abcd" }));
        // Display name lives in the store, not the strict config.
        let st = state(&Install::default());
        assert_eq!(st.providers.iter().find(|p| p.id == "my-relay").unwrap().name, "My Relay");

        // Rename only: no config write at all.
        let (_, w, _) = plan(&[edit("my-relay", "Relay!", "https://r.example.com/v1", "chat", None)], false).unwrap();
        assert!(w.is_empty());
        assert_eq!(state(&Install::default()).providers.iter().find(|p| p.id == "my-relay").unwrap().name, "Relay!");

        // Changing address + key of myproxy is mirrored into the generated models.json.
        let (d, w, _) = plan(&[edit("myproxy", "myproxy", "https://new.example.com/v1", "chat", Some("sk-new-proxy-9999"))], false).unwrap();
        assert!(lines(&d).contains("同步生成文件") && !lines(&d).contains("sk-new-proxy"));
        assert_eq!(w.len(), 2);
        let g = gen();
        assert_eq!(g["providers"]["myproxy"]["baseUrl"], "https://new.example.com/v1");
        assert_eq!(g["providers"]["myproxy"]["apiKey"], "sk-new-proxy-9999");
        assert_eq!(g["providers"]["other"], json!({ "baseUrl": "https://other.example.com" }));
        assert_eq!(cfg()["models"]["providers"]["myproxy"]["apiKey"], "sk-new-proxy-9999");

        // Deleting the default provider clears primary and its fallbacks, keeps the built-in fallback.
        let (d, _, _) = plan(&[Op::DeleteProvider { provider: "myproxy".into() }], false).unwrap();
        let t = lines(&d);
        assert!(t.contains("primary") && t.contains("myproxy/glm-4.6"), "{t}");
        let c = cfg();
        assert!(c["agents"]["defaults"]["model"].get("primary").is_none());
        assert_eq!(c["agents"]["defaults"]["model"]["fallbacks"], json!(["anthropic/claude-opus-4-6"]));
        assert_eq!(c["agents"]["defaults"]["workspace"], "~/work");
        assert_eq!(c["channels"], json!({ "telegram": { "enabled": true } }));
    }

    #[test]
    fn models_and_toggle() {
        let _g = setup("models", Some(STRICT));
        // Hide + show keeps the full definition.
        plan(&[Op::SetModelVisible { provider: "plain".into(), model: "gpt-x".into(), visible: false }], false).unwrap();
        assert_eq!(cfg()["models"]["providers"]["plain"]["models"], json!([]));
        plan(&[Op::SetModelVisible { provider: "plain".into(), model: "gpt-x".into(), visible: true }], false).unwrap();
        assert_eq!(cfg()["models"]["providers"]["plain"]["models"], json!([{ "id": "gpt-x", "name": "gpt-x" }]));
        // Add (name defaults to the id — required by OpenClaw) and edit.
        plan(&[Op::UpsertModel { provider: "plain".into(), model: ModelInput { id: "o5".into(), name: None, context: Some(400000), ..Default::default() } }], false).unwrap();
        assert_eq!(cfg()["models"]["providers"]["plain"]["models"][1], json!({ "id": "o5", "name": "o5", "contextWindow": 400000 }));
        plan(&[Op::UpsertModel { provider: "plain".into(), model: ModelInput { id: "o5".into(), name: Some("O5".into()), context: None, ..Default::default() } }], false).unwrap();
        assert_eq!(cfg()["models"]["providers"]["plain"]["models"][1]["name"], "O5");
        plan(&[Op::DeleteModel { provider: "plain".into(), model: "o5".into() }], false).unwrap();
        assert_eq!(cfg()["models"]["providers"]["plain"]["models"].as_array().unwrap().len(), 1);
        plan(&[Op::SetProviderModels { provider: "myproxy".into(), models: vec!["glm-5".into(), "z".into()] }], false).unwrap();
        let ms = cfg()["models"]["providers"]["myproxy"]["models"].clone();
        assert_eq!(ms[0]["maxTokens"], 32000);
        assert_eq!(ms[1], json!({ "id": "z", "name": "z" }));
        // glm-4.6 dropped → removed from fallbacks.
        assert_eq!(cfg()["agents"]["defaults"]["model"]["fallbacks"], json!(["anthropic/claude-opus-4-6"]));
        assert_eq!(cfg()["agents"]["defaults"]["model"]["primary"], "myproxy/glm-5");

        // Disable (dry run first) / enable.
        let before = std::fs::read(config_path()).unwrap();
        let off = Op::SetProviderEnabled { provider: "vault".into(), enabled: false };
        let (d, w, b) = plan(std::slice::from_ref(&off), true).unwrap();
        assert!(!d.groups.is_empty() && w.is_empty() && b.is_none());
        assert_eq!(std::fs::read(config_path()).unwrap(), before);
        plan(&[off], false).unwrap();
        assert!(cfg()["models"]["providers"].get("vault").is_none());
        let st = state(&Install::default());
        let v = st.providers.iter().find(|p| p.id == "vault").unwrap();
        assert!(!v.enabled && v.has_key);
        plan(&[Op::SetProviderEnabled { provider: "vault".into(), enabled: true }], false).unwrap();
        assert_eq!(cfg()["models"]["providers"]["vault"]["apiKey"]["source"], "exec");
        assert!(plan(&[Op::SetCurrentProvider { provider: "vault".into() }], true).is_err());
    }

    #[test]
    fn roundtrip_keeps_bytes() {
        let _g = setup("roundtrip", Some(STRICT));
        plan(&[Op::UpsertModel { provider: "plain".into(), model: ModelInput { id: "gpt-x".into(), name: Some("GPT X".into()), context: None, ..Default::default() } }], false).unwrap();
        plan(&[Op::UpsertModel { provider: "plain".into(), model: ModelInput { id: "gpt-x".into(), name: Some("gpt-x".into()), context: None, ..Default::default() } }], false).unwrap();
        assert_eq!(std::fs::read_to_string(config_path()).unwrap(), STRICT);
    }

    #[test]
    fn missing_file_is_created() {
        let _g = setup("missing", None);
        let st = state(&Install::default());
        assert!(!st.readonly && st.providers.is_empty());
        plan(&[Op::UpsertProvider { provider: ProviderInput { id: None, name: "r".into(), base_url: "https://r.example.com".into(), api: "anthropic".into(), api_key: None, models: vec![], key_from_library: None, official_auth: None } }], false).unwrap();
        assert_eq!(cfg(), json!({ "models": { "providers": { "r": { "baseUrl": "https://r.example.com", "api": "anthropic-messages", "models": [] } } } }));
    }

    /// Read-only look at the real machine: `cargo test --lib dump_openclaw -- --ignored --nocapture`.
    #[test]
    #[ignore]
    fn dump_openclaw() {
        let inst = detect();
        println!("installed={} version={:?}", inst.installed, inst.version);
        let st = state(&inst);
        println!("dir={} readonly={} files={:?}", st.config_dir, st.readonly, st.files);
        for p in &st.providers {
            println!("  [{}] {} api={} host={} key={} enabled={} models={:?}", p.id, p.name, p.api, p.host, p.has_key, p.enabled, p.models.iter().map(|m| (&m.id, m.visible)).collect::<Vec<_>>());
        }
        for k in &st.current {
            println!("  {} = {}", k.k, k.v);
        }
        println!("notes={:?}", st.notes);
        let op = Op::UpsertProvider { provider: ProviderInput { id: None, name: "Dump Probe".into(), base_url: "https://probe.example.com/v1".into(), api: "chat".into(), api_key: Some("sk-dump-probe-0000".into()), models: vec!["m".into()], key_from_library: None, official_auth: None } };
        let (d, written, backup) = plan(&[op], true).unwrap();
        for g in &d.groups {
            for l in &g.lines {
                println!("  diff {} | {}", g.file, l.text);
            }
        }
        assert!(written.is_empty() && backup.is_none());
    }
}
